### ISSUE TITLE
Generating docker-compose with wrong datasource

### ISSUE THREAD

**Issue by saade** [notiz-dev/nestjs-prisma#11]
Hi, i noticed that the cli is creating a wrong datasource inside `docker-compose.yml`.

As you can see, i selected `mysql` as a datasource, but inside the docker-compose.yml file, it installed `postgresql` as a datasource

![image](https://user-images.githubusercontent.com/14329460/135461958-67a56f61-a9e3-4a9d-8240-507ca3110e88.png)

**Comment by marcjulian** [comment]
@saade hey thanks for bringing that up. Until now only postgres db is supported in the `docker-compose.yml` file, see https://github.com/marcjulian/nestjs-prisma/blob/main/schematics/nestjs-prisma/templates/docker/docker-compose.yml

Do you like add mysql support as well?

**Comment by saade** [comment]
hey!, sorry i didn't see that, MB for not paying attention to this.

I'm really busy right now, but sure, I can have a look at this in my spare time! =)

**Comment by marcjulian** [comment]
No worries :) If you already have a valid docker-compose.yml with mysql you can drop it in here and either you or me will implement it.

**Comment by saade** [comment]
Laravel uses a url to get contents for their Dockerfile, maybe we can do something similar as this repo is public. We can setup some files here in the repo to get the data from, or maybe a github page.

Have a look:

Default setup script:
https://laravel.build/example-app

setup with mysql and redis:
https://laravel.build/example-app?with=mysql,redis

setup with pgsql:
https://laravel.build/example-app?with=pgsql


We can do maybe something like this:

With mysql:
https://raw.githubusercontent.com/marcjulian/nestjs-prisma/main/schematics/nestjs-prisma/templates/docker/docker-compose-MYSQL.yml

With sqlite:
https://raw.githubusercontent.com/marcjulian/nestjs-prisma/main/schematics/nestjs-prisma/templates/docker/docker-compose-SQLITE.yml

With pgsql:
https://raw.githubusercontent.com/marcjulian/nestjs-prisma/main/schematics/nestjs-prisma/templates/docker/docker-compose-PGSQL.yml

And just fetch that url during installation based on user input =)

**Comment by marcjulian** [comment]
@saade mysql is now supported in [0.14.0](https://github.com/marcjulian/nestjs-prisma/releases/tag/v0.14.0). Give it a try.

**Comment by saade** [comment]
sweet!
