### ISSUE TITLE
prisma-client-exception filter 

### ISSUE THREAD

**Issue by MohannadBahaa** [notiz-dev/nestjs-prisma#14]
Hello there,

## Problem
nestjs-prisma error filter is handling only `PrismaClientKnownRequestError`

## Solution
Handling other client error types such as :
```
PrismaClientInitializationError
PrismaClientRustPanicError
PrismaClientUnknownRequestError
PrismaClientValidationError
```

do you want me to raise **_PR_** for this issue :)

**Comment by marcjulian** [comment]
@MohannadBahaa hey would be greate if you can create a PR! Do you want to include those erros in one filter or would it be for each error one filter?

**Comment by MohannadBahaa** [comment]
Hey @marcjulian, tbh right now I don't know what approach I will follow, I will create a PR and after that any feedback is welcome 🙏

**Comment by marcjulian** [comment]
@MohannadBahaa feel free to reopen this issue when you work on it!
