### ISSUE TITLE
How to define prisma middlewares?

### ISSUE THREAD

**Issue by AttilaSATAN** [notiz-dev/nestjs-prisma#15]
Is there a way to reach the underlying `PrismaClient` instance for using `prismaClient.$use` method or is there any other way to manipulate custom middlewares?

**Comment by marcjulian** [comment]
Hi @AttilaSATAN here is an example to add Prisma middlewares using the `PrismaService` in the `main.ts`.

```ts
// src/main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PrismaService } from 'nestjs-prisma';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const prismaService: PrismaService = app.get(PrismaService);
  prismaService.$use(async (params, next) => {
    // your middleware
  });

  await app.listen(3000);
}
bootstrap();
```

**Comment by marcjulian** [comment]
Perhaps we could even introduce to pass middlewares via the `PrismaModule`.

**Comment by marcjulian** [comment]
@AttilaSATAN i added support for passing middlewares directly through PrismaModule. Find the documentation and example here https://github.com/notiz-dev/nestjs-prisma#prisma-middleware

You can test it out with the dev release `0.15.0-dev.2`
