### ISSUE TITLE
Shutdown hooks

### ISSUE THREAD

**Issue by smitssjors** [notiz-dev/nestjs-prisma#16]
Does this package handle the shutdown hooks as described [in the nest docs](https://docs.nestjs.com/recipes/prisma#issues-with-enableshutdownhooks)?
I can't find it when looking at the source code but maybe the documentation is outdated.

**Comment by marcjulian** [comment]
@smitssjors no this is not supported. Do you like to add this feature? PRs are welcome!

**Comment by marcjulian** [comment]
@smitssjors test it with the latest dev release `nestjs-prisma@0.15.0-dev.0`
