### ISSUE TITLE
Specify non-default prisma client to import / use multiple prisma clients

### ISSUE THREAD

**Issue by singerla** [notiz-dev/nestjs-prisma#18]
Hi!

Is it possible to specify a different client (and therefore allow usage of multiple prisma clients)? I have two different schemata generating each into a separate directory using `output` in my `schema.prisma`-files:

```
generator client {
  provider = "prisma-client-js"
  output   = "prisma/client1"
  // output   = "prisma/client2"
}
```
I need to import those by addresing e.g.
`import { PrismaClient } from '../prisma/client1';`

It seems as if PrismaClient import within nestjs-prisma is directly tied to `import { PrismaClient } from '@prisma/client';`, which was ok if I use the default output. Is there any way to handle this more flexible?

Thanks in advance!

**Comment by singerla** [comment]
I could find good advice here:
https://darioielardi.dev/schema-based-multi-tenancy-with-nestjs-and-prisma

In general:
https://github.com/Errorname/prisma-multi-tenant

Thanks a lot for your great work, keep on going!

**Comment by marcjulian** [comment]
@singerla thanks for raising this feature. Yes as you noticed the library is directly importing  `import { PrismaClient } from '@prisma/client';`. Thus, allowing us to directly access all functions from `PrismaService`.

Not sure if its possible to change the import for the extension of `PrismaService`

```ts
import {
  Injectable,
  OnModuleInit,
} from '@nestjs/common';
import { PrismaClient } from '@prisma/client'; // will need to make this configureable, not sure if thats possible

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
...
}
```

Glad you found some good advice. When I find some time I'll look into solving this feature.
