### ISSUE TITLE
Use PrismaClientExceptionFilter get error `response.status(...).json is not a function` when FastifyAdapter as app

### ISSUE THREAD

**Issue by liaosankai** [notiz-dev/nestjs-prisma#20]
I got error  `response.status(...).json is not a function` in PrismaClientExceptionFilter if I use FastifyAdapter as my app. How about compatible with fastify?

**Comment by marcjulian** [comment]
@liaosankai thanks for reporting this issue. I haven't used it with fastify yet, but makes sense that you receive the error as the filter uses `Response` from express https://github.com/notiz-dev/nestjs-prisma/blob/main/lib/prisma-client-exception.filter.ts#L4.

We should add an exception filter for fastify for examle `PrismaClientFasitfyExceptionFilter`. Here is [an example](https://stackoverflow.com/a/61842971) how to get and manipulate the response for fastify.

Do you want to add this filter for fastify in a PR? Happy to help out.
