### ISSUE TITLE
Exception Filter compatible with GraphQL

### ISSUE THREAD

**Issue by marcjulian** [notiz-dev/nestjs-prisma#22]
The current `PrismaClientExceptionFilter` is not compatible with GraphQL.
Improve the filter to support GraphQL as well, more infos in the docs https://docs.nestjs.com/graphql/other-features#exception-filters

**Comment by suryatmodulus** [comment]
@marcjulian I've created a  pull request to fix this [https://github.com/notiz-dev/nestjs-prisma/pull/29](https://github.com/notiz-dev/nestjs-prisma/pull/29)
