### ISSUE TITLE
How can I log query params?

### ISSUE THREAD

**Issue by J-Rigondo** [notiz-dev/nestjs-prisma#23]
hello
I can't find way to handle emit type: 'event'.
thank you

PrismaModule.forRoot({
      isGlobal: true,
      prismaServiceOptions: {
        // middlewares: [loggingMiddleware()],
        prismaOptions: {
          log: [
            { emit: 'stdout', level: 'query' },
            { emit: 'stdout', level: 'info' },
            { emit: 'stdout', level: 'warn' },
            { emit: 'stdout', level: 'error' },
          ],
        },
      },
    }),

 prisma:query BEGIN
[start:dev] prisma:query INSERT INTO `team_seas`.`user` (`id`,`name`,`email`,`password`,`role`) VALUES (?,?,?,?,?)

**Comment by marcjulian** [comment]
@J-Rigondo hi, is that possible via `PrismaClient`? I am exposing the same option object for the `forRoot` method.

I couldn't find anything in the prisma docs about [log](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) query params.

**Comment by marcjulian** [comment]
Maybe this is what you are looking for:

```ts
const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
});

prisma.$on('query', (e) => {
  console.log('Query: ' + e.query);
  console.log('Params: ' + e.params);
  console.log('Duration: ' + e.duration + 'ms');
});
```

One idea comes to mind in `main.ts` to access the `PrismaService`, like we do with the `enableShutdownHooks` method, and than define `$on('query' ...` :

```ts
// main.ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const prismaService: PrismaService = app.get(PrismaService);
  prismaService.$on('query', (e) => {}); // 👈 currently type error

  await app.listen(port);
}
```

The problem is that the types are currently not correct expose for the PrismaClient when the log levels are added.

I would appreciate a PR, if you have an idea how to fix it.

**Comment by marcjulian** [comment]
Can be testet in the latest dev release [0.18.0-dev.1](https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.18.0-dev.1).
