### ISSUE TITLE
Use prisma db pull

### ISSUE THREAD

**Issue by ClementineZou** [notiz-dev/nestjs-prisma#24]
Hi, I used `PrismaModule.forRootAsync` to set up my database URL. But it can't work when I ran `prisma db pull` in console. Should I still keep a `.env` file in my directory?

**Comment by marcjulian** [comment]
Hi @AuroraAndersson what happens when you use `prisma db pull`. By default `PrismaClient` is looking for a `.env` file. If you have a reproduction repo that would help me to figure out the error.

**Comment by marcjulian** [comment]
Please provide more information about your problem. In the meantime I'll close this issue.
