### ISSUE TITLE
support Prisma v4

### ISSUE THREAD

**Issue by abrl91** [notiz-dev/nestjs-prisma#28]
Hey, is there any intention to support Prisma 4 in the future, and if so, when?
We want to upgrade our platform, but nestjs-prisma  has a peer-dependency with prisma versions "^2.0.0 || ^3.0.0"

![Screen Shot 2022-07-18 at 14 59 59](https://user-images.githubusercontent.com/39680385/179507663-88c44a42-fac3-4fde-b147-1b4caaa11421.png)

**Comment by marcjulian** [comment]
@abrl91 this is already updated and released currently as [dev](https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.17.0-dev.0) release.

Please try

```bash
npm i nestjs-prisma@dev
```

**Comment by abrl91** [comment]
@marcjulian Thank you! 
Just to be sure I understood you right, this is not the latest version of nestjs-prisma, meaning that when I run npm install nestjs-prisma the installed version is 0.16.0. I have to install it with `@dev`

**Comment by marcjulian** [comment]
Yes correct. Version 0.16.0 is the latest version and 0.17.0-dev.1 is the latest dev release. 
I will promote the 0.17.0 to the latest version after I have some feedback.

**Comment by marcjulian** [comment]
@abrl91 I have released 0.17.0 with support for Prisma 4 and Nest 9.

**Comment by abrl91** [comment]
@marcjulian Thanks for the update 😃
