### ISSUE TITLE
Add support for fastify platform

### ISSUE THREAD

**Issue by refactorraccoon** [notiz-dev/nestjs-prisma#33]
Right now it's only possible to use this module with express, it would be great to have the ability to use all this with fastify since most of the source code would be the same.

```
 WARN  Issues with peer dependencies found
.
├─┬ nestjs-prisma 0.18.0
│ ├── ✕ missing peer @nestjs/platform-express@"^7.0.0 || ^8.0.0 || ^9.0.0"
├─┬ @nestjs/testing 8.4.6
│ └── ✕ missing peer @nestjs/platform-express@^8.0.0
└─┬ @nestjs/core 8.4.6
  └── ✕ missing peer @nestjs/platform-express@^8.0.0
Peer dependencies that should be installed:
  @nestjs/platform-express@">=8.0.0 <9.0.0" 
  ```

**Comment by marcjulian** [comment]
Thanks for reporting. `@nestjs/platform-express` was a peerDeps but was not used.

**Comment by marcjulian** [comment]
You can test it in the latest dev release `nestjs-prisma@0.19.0-dev.0`. Please let me know if this solved the dependency warnings.
