### ISSUE TITLE
How to access $on in PrismaService?

### ISSUE THREAD

**Issue by Kasheftin** [notiz-dev/nestjs-prisma#35]
Hi,
for the demo purpose I need to log queries fully like it's shown in this approach: https://github.com/prisma/prisma/issues/5026#issuecomment-982157335.
How to do that?
On my opinion something like this should work:
```javascript
import { NestFactory } from '@nestjs/core'
import { PrismaService } from 'nestjs-prisma'
import { AppModule } from '@/app.module'

async function bootstrap() {
  const app = await NestFactory.create(AppModule)
  const prismaService = app.get(PrismaService)
  await prismaService.onModuleInit()
  prismaService.$on('query', e => {
    console.log(e)
  })
  await app.listen(config.get('server.port'))
}
bootstrap()
````
It does not give any typescript error (PrismaService extends PrismaClient) but it does not log anything.

**Comment by marcjulian** [comment]
Hi @Kasheftin yes that seems to be right. Additionally you have to pass the `query` log option to the `PrismaClient`. All `PrismaClient` options are available in the `PrismaModule.forRoot(..)` method.

```ts
import { Module } from '@nestjs/common';
import { PrismaModule } from 'nestjs-prisma';

@Module({
  imports: [
    PrismaModule.forRoot({
      prismaServiceOptions: {
        prismaOptions: {
          log: [ 
            {
              emit: 'event',
              level: 'query',
            },
          ],
        },
      },
    }),
  ],
})
export class AppModule {}
```

And little modification of your bootstrap function. You don't need to call `await prismaService.onModuleInit()`, `onModuleInit()` is a Nest lifecycle hook and would be managed by Nest itself.

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PrismaService } from 'nestjs-prisma';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const prismaService: PrismaService = app.get(PrismaService);
  prismaService.$on('query', (e) => {
    console.log(e);
  });

  await app.listen(process.env.PORT || 3000);
}
bootstrap();
```

Related to https://github.com/notiz-dev/nestjs-prisma/issues/23#issuecomment-1171075230

**Comment by Kasheftin** [comment]
Thanks, it works.

**Comment by marcjulian** [comment]
I will open it again to add this to the documentation.

**Comment by marcjulian** [comment]
Added to the docs https://nestjs-prisma.dev/docs/prisma-logging/
