### ISSUE TITLE
Error: Collection "nestjs-prisma" cannot be resolved

### ISSUE THREAD

**Issue by zhbn** [notiz-dev/nestjs-prisma#37]
>nest add nestjs-prisma
✔ Package installation in progress... ☕
Starting library setup...
Error: Collection "nestjs-prisma" cannot be resolved.

Failed to execute command: node nestjs-prisma:nest-add --source-root="src" C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\@nestjs\cli\bin\nest.js add nestjs-prisma

**Comment by marcjulian** [comment]
Hi @zhbn, unfortunately I don't use Windows so I cannot test it.

Maybe we can still figure something out.
Which node version are you using? 
Does any other `nest add` command work? (e.g `nest add @nestjs/azure-storage`, `nest add @nestjs/azure-func-http` - just for testing)

**Comment by zhbn** [comment]
it resovled :
1. yarn add nestjs-prisma
2. nest add nestjs-prisma
only nest add nestjs-prisma can not work

**Comment by marcjulian** [comment]
`yarn add` is not the same as `nest add`. `nest add` executes the schematics for additional setup steps. Whereas `yarn add` only installs the dependency `nestjs-prisma`.

**Comment by marcjulian** [comment]
I can't test and fix this right now, as I am only using a Mac.
