### ISSUE TITLE
Prisma exception filter uses text/html content type

### ISSUE THREAD

**Issue by Loskir** [notiz-dev/nestjs-prisma#38]
When using in http mode, PrismaExceptionFilter uses text/html content type instead of application/json.

I inspected the source code and found the cause:

https://github.com/notiz-dev/nestjs-prisma/blob/main/lib/prisma-client-exception.filter.ts#L95

Also why doesn't it throw HttpException and instead writes the response directly?

**Comment by marcjulian** [comment]
Hi @Loskir followed the exception filter [docs](https://docs.nestjs.com/exception-filters#exception-filters-1) from NestJS to use `response.status().send()`. Perhaps we can change the content type to `application/json` with the current approach or change it to throw a HttpException instead. Do you like to create a PR?

**Comment by Loskir** [comment]
Good! I'll refactor it to throw HttpException instead and create a PR

**Comment by marcjulian** [comment]
Sure try it out! PRs are welcome.
