### ISSUE TITLE
Two different connections

### ISSUE THREAD

**Issue by cursan-a** [notiz-dev/nestjs-prisma#41]
Hi,

On my project I need to open 2 postgresql connections (1 master, 1 read replica for analytics). I can't figure how to give a custom name when I instantiate a `PrismaModule` that allow me to inject `PrismaService` with the specified name.

I need something like :
whatever.module.ts
```ts
@Module({
  imports: [
    PrismaModule.forRootAsync({
      name: 'ANALYTICS_DATABASE'
...
```

whatever.service.js
``` ts
@Injectable()
export class WhateverService {
  @Inject("ANALYTICS_DATABASE")
  private readonly prismaAnalytics!: PrismaService;
...
```

Is that possible with your implementation ?

Thank you in advance

**Comment by marcjulian** [comment]
Hi @cursan-a, checkout https://github.com/notiz-dev/nestjs-prisma/pull/40 as this is a new feature and you will need to use `CustomPrismaModule` and `CustomPrismaService`. Let me know if it works for you.

**Comment by marcjulian** [comment]
Closing this for now as it has the same solution as #31.
