### ISSUE TITLE
Support Prisma Client Extensions (Preview)

### ISSUE THREAD

**Issue by marcjulian** [notiz-dev/nestjs-prisma#43]
Prisma release with in version [4.7.0](https://github.com/prisma/prisma/releases/tag/4.7.0) [Prisma Client Extensions (Preview)](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions)

This should be possible with the new `CustomPrismaModule`/`CustomPrismaService` (https://github.com/notiz-dev/nestjs-prisma/pull/40) where you can need to provide a `PrismaClient` instance.

**Comment by marcjulian** [comment]
Example to use Prisma Client Extensions.

1. Install Prisma Client v4.7.0 or later and install nestjs-prisma@v0.20.0-dev.2

2. Enable `clientExtensions` preview

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

model User {
  id    String  @id @default(cuid())
  email String  @unique
  name  String?
}
```

3. Create a file for the Prisma extension `prisma.extension.ts`

```ts
import { PrismaClient } from '@prisma/client';

/**
 * TS error: "Inferred type of this node exceeds the maximum length the compiler will serialize" with "declaration": true in tsconfig
 *
 * Change "declaration": false in `tsconfig.json`
 *
 * https://github.com/prisma/prisma/issues/16536#issuecomment-1332055501
 */
export const prismaClient = new PrismaClient().$extends({
  model: {
    user: {
      findByEmail: async (email: string) => {
        return prismaClient.user.findFirstOrThrow({ where: { email } });
      },
    },
  },
});

export type prismaClient = typeof prismaClient;
```

4. Change `declaration` to `false` in your `tsconfig.json` - workaround for https://github.com/prisma/prisma/issues/16536#issuecomment-1332055501

`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.`

5. Use `CustomPrismaModule.forRootAsync`

```ts
import { Module } from '@nestjs/common';
import { CustomPrismaModule } from 'nestjs-prisma';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { prismaClient } from './prisma.extension';

@Module({
  imports: [
    CustomPrismaModule.forRootAsync({
      name: 'PrismaService',
      useFactory: () => {
        return prismaClient;
      },
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

6. Inject `CustomPrismaService` into your controller/service

```ts
import { Inject, Injectable } from '@nestjs/common';
import { CustomPrismaService } from 'nestjs-prisma';
import { prismaClient } from './prisma.extension';

@Injectable()
export class AppService {
  constructor(
    // ✅ use `prismaClient` from extension for correct type-safety
    @Inject('PrismaService')
    private prismaService: CustomPrismaService<prismaClient>,
  ) {}

  users() {
    return this.prismaService.client.user.findMany();
  }

  user(userId: string) {
    // 🦾 use new `findByEmail`
    return this.prismaService.client.user.findByEmail(userId);
  }
}
```

**Comment by shoaibsharif** [comment]
Thank you for the example. That helps a lot to understand how to use extension with new dev release version, but is there a way we can use extension in existing PrismaService or anyway to override that?

**Comment by marcjulian** [comment]
hi @shoaibsharif haven't found a way to use extension with the existing `PrismaService` as the service is directly extended by the default `PrismaClient`. For now you need to use `CustomPrismaService`.
