### ISSUE TITLE
Golbal module from `forRoot`

### ISSUE THREAD

**Issue by lxmfly123** [notiz-dev/nestjs-prisma#44]
According to [nestjs module naming community guidelines](https://docs.nestjs.com/fundamentals/dynamic-modules#community-guidelines), it's propper to return a global module by method `forRoot`.

**Comment by marcjulian** [comment]
Hi @lxmfly123 yes fair point. I think I remember using `ConfigModule.forRoot` as a reference. 

You need to import `ConfigModule` in other modules or declare it as [global](https://docs.nestjs.com/techniques/configuration#use-module-globally):

```ts
ConfigModule.forRoot({
  isGlobal: true,
})
```

The same applies for the `PrismaModule`

```ts
PrismaModule.forRoot({
  isGlobal: true,
})
```

**Comment by lxmfly123** [comment]
I think that's a flaw in nest doc, because: 

1. It is controversial with the naming guidelines
2. The name `forRoot` itself has already suggested `{ isGlobal: true }`
3. Other official modules like @nestjs/typeorm and @nestjs/graphql do not need pass `{ isGlobal: true }` to `forRoot` to be global

Ultimately, of course, the guidelines are just guidelines. Your module, your rules.
