### ISSUE TITLE
Two clients

### ISSUE THREAD

**Issue by luluhoc** [notiz-dev/nestjs-prisma#47]
Does it support 2 clients?

Like described in this issue https://github.com/prisma/prisma/issues/2443#issuecomment-630679118

**Comment by marcjulian** [comment]
Hi @luluhoc yes supported with the latest version 0.20.0. See the [docs](https://nestjs-prisma.dev/docs/custom-prisma-client-location/#multiple-prisma-clients) how to use it.

**Comment by luluhoc** [comment]
> Hi @luluhoc yes supported with the latest version 0.20.0. See the [docs](https://nestjs-prisma.dev/docs/custom-prisma-client-location/#multiple-prisma-clients) how to use it.

Thanks, Great work

**Comment by marcjulian** [comment]
Thank you!
