### ISSUE TITLE
nest add nestjs-prisma error Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by masterbater** [notiz-dev/nestjs-prisma#48]
⠴ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/GWAPOKO/.npm/_logs/2023-01-19T07_57_49_031Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node nestjs-prisma:nest-add --source-root="src" /Users/GWAPOKO/.nvm/versions/node/v18.12.0/bin/node /Users/GWAPOKO/Library/pnpm/global/5/node_modules/@nestjs/cli/bin/nest.js add nestjs-prisma

**Comment by masterbater** [comment]
Using npm instead of pnpm solve this error, hopefully you can support pnpm

**Comment by Keeqler** [comment]
Same problem here.
