### ISSUE TITLE
Nest can't resolve dependencies of the PrismaClientExceptionFilter 

### ISSUE THREAD

**Issue by sidneip** [notiz-dev/nestjs-prisma#51]
i am getting error when i am configure PrismaClientExceptionFilter in app.module.ts

[Nest] 32200  - 01/02/2023, 11:14:18     LOG [NestFactory] Starting Nest application...
[Nest] 32200  - 01/02/2023, 11:14:18     LOG [InstanceLoader] PrismaModule dependencies initialized +76ms
[Nest] 32200  - 01/02/2023, 11:14:18   ERROR [ExceptionHandler] Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

Error: Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

```
providers: [
    {
      provide: APP_FILTER,
      useClass: PrismaClientExceptionFilter,
    },
    AppService,
  ],
```

**Comment by marcjulian** [comment]
Hi @sidneip are you generating the Prisma Client to a custom location?

`PrismaClientExceptionFilter` relies on `@prisma/client` to specify the exceptions to handle.

https://github.com/notiz-dev/nestjs-prisma/blob/a3aebd9b2a1d1df9c55e5fddf0257893f68ffd05/lib/prisma-client-exception.filter.ts#L9-L18

**Comment by sidneip** [comment]
No, i did setup default.

**Comment by marcjulian** [comment]
Did you run `npx prisma generate`? Maybe the prisma client hasn't been generated.

**Comment by marcjulian** [comment]
Nevermind, I tried it out again and also got the same error as you experiencing.

If you want to use `APP_FILTER` you need to us a factory instead of the class

```ts
providers: [
    AppService,
    {
      provide: APP_FILTER,
      useFactory: ({ httpAdapter }: HttpAdapterHost) => {
        return new PrismaClientExceptionFilter(httpAdapter);
      },
      inject: [HttpAdapterHost],
    },
  ],
```

Alternative would be to instantiate `PrismaClientExceptionFilter` in `main.ts`. I will update the docs. Thanks for reporting the bug.

**Comment by marcjulian** [comment]
I updated the docs for applying `APP_FILTER` correctly 👉 https://nestjs-prisma.dev/docs/exception-filter/#app_filter

**Comment by sidneip** [comment]
Thanks @marcjulian 

I did one test and i have success.
