### ISSUE TITLE
document css: cannot see some text

### ISSUE THREAD

**Issue by vagreargnatry** [notiz-dev/nestjs-prisma#52]
Hello, in this page I cannot see some text: https://nestjs-prisma.dev/docs/exception-filter/

I try to close `color: inherit` to make the text visible.
![css](https://user-images.githubusercontent.com/104709852/217765287-5be66b3c-e4de-492f-a527-fdd3a0345479.png)

**Comment by marcjulian** [comment]
@vagreargnatry thanks for reporting!
