### ISSUE TITLE
Errors coming using PrismaClientExceptionFilter at global level.

### ISSUE THREAD

**Issue by jd4u** [notiz-dev/nestjs-prisma#57]
Errors coming using PrismaClientExceptionFilter at global level. Disable the use and all works well.

Error: `TypeError: Right-hand side of 'instanceof' is not an object at is InstanceOf (node_modules/@nestjs/core/exceptions/exceptions-handler.js:28:54)`

Following code is activated in request that causes the issue.
```
throw new BadRequestException({
                description: 'Insufficient Credential Details',
                status: HttpStatus.BAD_REQUEST,
});
```

Before upgrade to prisma 4.14.0, this worked well..!! nestjs-prisma is 0.20.0

**Comment by marcjulian** [comment]
Hi @jd4u I cannot reproduce this error. I have updated the [Basic Example](https://github.com/notiz-dev/nestjs-prisma/tree/main/examples/basics) to Prisma 4.14.0 and it catches the error when calling [GET localhost:3000/test](http://localhost:3000/test)

**Comment by marcjulian** [comment]
Closing for now. Please provide a reproduction repository.

**Comment by trungtin** [comment]
In our monorepo setup, Prisma is defined in a separate module. As a result, when nestjs-prisma defines the filter like this:
```
@Catch(Prisma?.PrismaClientKnownRequestError)
export class PrismaClientExceptionFilter extends BaseExceptionFilter {
    ...
}
```

Prisma?.PrismaClientKnownRequestError is undefined, leading to the error: `TypeError: Right-hand side of 'instanceof' is not an object at is InstanceOf`

**Solution**: Extend the base filter and explicitly import Prisma from your module:
```
import { PrismaClientExceptionFilter as BasePrismaClientExceptionFilter } from 'nestjs-prisma';
import { Prisma } from '@your-org/prisma';

@Catch(Prisma.PrismaClientKnownRequestError)
export class PrismaClientExceptionFilter extends BasePrismaClientExceptionFilter {}
```
