### ISSUE TITLE
Use of $extends

### ISSUE THREAD

**Issue by ikbenignace** [notiz-dev/nestjs-prisma#64]
Hi

I want the service to always extends a specific extension I use

Currently I have to do something like this:
```
export const prismaClient = globalClient.$extends(
   fieldEncryptionExtension()
 )
```

Is there a way to do this with this package?

**Comment by marcjulian** [comment]
Hi @ikbenignace, have a look at the [extension example](https://github.com/notiz-dev/nestjs-prisma/tree/main/examples/extensions) and the docs about how to use [Prisma Client Extension with nestjs-prisma](https://nestjs-prisma.dev/docs/prisma-client-extensions/). This library supports the use of `$extends`

https://github.com/notiz-dev/nestjs-prisma/blob/4319bd1cf6f8966b88b353e00778f88652070e55/examples/extensions/src/prisma.extension.ts#L13-L22

**Comment by marcjulian** [comment]
Closing for now. Please provide more information if you have more questions.
