### ISSUE TITLE
When will nestjs 10 be supported?

### ISSUE THREAD

**Issue by Jerry-wangjie** [notiz-dev/nestjs-prisma#66]
nest add nestjs-prisma
▹▹▹▹▸ Package installation in progress... ☕
Failed to execute command: npm install --save nestjs-prisma@latest
✖ Package installation in progress... ☕
Unable to install library nestjs-prisma because package did not install. Please check package name.

npm install nestjs-prisma
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nestjs-prisma-demo@0.0.1
npm ERR! Found: @nestjs/common@10.0.3
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.0 || ^8.0.0 || ^9.0.0" from nestjs-prisma@0.20.1
npm ERR! node_modules/nestjs-prisma
npm ERR!   nestjs-prisma@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

**### When will nestjs 10 be supported?**

**Comment by marcjulian** [comment]
nestjs 10 will be supported with the next version (https://github.com/notiz-dev/nestjs-prisma/issues/60#issuecomment-1597462348) you can test it with the dev release:

```bash
npm i nestjs-prisma@0.21.0-dev.2
```

**Comment by marcjulian** [comment]
This has been released with [0.21.0](https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.21.0)
