### ISSUE TITLE
nestjs 8.0.0 support

### ISSUE THREAD

**Issue by maxerbox** [notiz-dev/nestjs-prisma#7]
Dear Marc,

Could you update peer dependencies for the package with the release of nestjs 8.0.0 please ?

Regards,

Maxerbox

**Comment by marcjulian** [comment]
@maxerbox try out the latest dev release, I have updated it to support NestJS 8.x.

```bash
nest add nestjs-prisma@dev
npm i nestjs-prisma@dev
```

I will release soon a new version

**Comment by marcjulian** [comment]
New version [0.13.0](https://github.com/marcjulian/nestjs-prisma/releases/tag/v0.13.0) is available and supports NestJS 8.0.0.
