### ISSUE TITLE
PrismaService generator generates deprecated code

### ISSUE THREAD

**Issue by NoahMarconi** [notiz-dev/nestjs-prisma#71]
`enableShutdownHooks` is no longer required:

https://github.com/prisma/prisma-examples/issues/4931

**Comment by marcjulian** [comment]
Hi @NoahMarconi test out the latest [dev version](https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.22.0-dev.0) as the`enableShutdownHooks` has been removed.

**Comment by NoahMarconi** [comment]
awesome, will close this ticket and look out for the release

**Comment by marcjulian** [comment]
@NoahMarconi [0.22.0](https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.22.0) has been released.
