### ISSUE TITLE
Extensions: `create` and `update` broken

### ISSUE THREAD

**Issue by adamnyberg** [notiz-dev/nestjs-prisma#76]
Hey,

Maybe it is something wrongly configured on my system but when I try to use the methods `create` and `update`, typescript can not compile the project.

Steps to reproduce:
1. Fork this repo.
2. Add the following method to the `AppService` in `examples/extentions/src/app.service.ts`
```typescript
createUser(data: { email: string; name?: string }) {
    return this.prismaService.client.user.create(data);
}
```
3. Run `npm run build`

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Am I using the `this.prismaService.client.user.create` wrong?

**Comment by marcjulian** [comment]
Hi @adamnyberg you need to pass data as an object property to the `user.create`, read more about `create` [Create a single record with Prisma Client](https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-a-single-record)

```ts
createUser(data: { email: string; name?: string }) {
 return this.prismaService.client.user.create({ data });
}
```
