### ISSUE TITLE
Bump prisma version

### ISSUE THREAD

**Issue by mits87** [notiz-dev/nestjs-prisma#81]
Hi!

First of all thanks for the great package. 
Would you mind to bump prisma and @prisma/client packages to the latest version?

thanks in advance.

**Comment by marcjulian** [comment]
Hi @mits87, Prisma is updated will let you know when I cut a new release. 
Is it somehow required for you to have it update to the latest prisma version?

The `peerDependencies` should satisfy all minor releases of 5.x.x

```
    "@prisma/client": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0",
    "prisma": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
```

**Comment by marcjulian** [comment]
Try out the latest dev release

```bash
npm i nestjs-prisma@0.23.0-dev.0
```
