### ISSUE TITLE
Link on `middleware` broken

### ISSUE THREAD

**Issue by justinxia6dot5** [notiz-dev/nestjs-prisma#82]
This should be an easy fix, currently, the link at https://nestjs-prisma.dev/docs/configuration/#prismaserviceoptionsmiddlewares is not pointing to https://nestjs-prisma.dev/docs/prisma-middleware/, which was causing some confusion when I was doing research on this topic. The issue is an extra "s". Thank you!

**Comment by marcjulian** [comment]
Thanks for reporting!
