### ISSUE TITLE
Support for Multiple Database Clients in NestJS Prisma Module

### ISSUE THREAD

**Issue by giorgijanashia** [notiz-dev/nestjs-prisma#90]
#### Problem:
I'm currently working on a NestJS project that involves interacting with two separate PostgreSQL databases, each with its own Prisma schema (`schema1.prisma` and `schema2.prisma`). However, it's not clear how to configure `nestjs-prisma` to work with multiple databases and separate Prisma schemas.

#### Expected Behavior:
I expect `nestjs-prisma` to provide support for multiple PostgreSQL databases, allowing seamless integration with different databases in a single NestJS application. Each database corresponds to a separate Prisma schema, and I want to use `PrismaService` instances configured for each schema independently.

#### Additional Context:

- I have two Prisma schemas (`schema1.prisma` and `schema2.prisma`), each representing a different PostgreSQL database.
- I've attempted to create separate `PrismaOptionsFactory` implementations for each schema, but I'm unsure how to correctly configure the `PrismaModule` in `app.module.ts` to achieve the desired behavior.
- It would be beneficial to have clear documentation or examples demonstrating how to configure `nestjs-prisma` for multiple PostgreSQL databases with separate Prisma schemas.

### Suggestion:

It might be worth exploring if there's an existing package or library that provides support for multiple databases in NestJS with functionality similar to `nestjs-prisma`. If such a package exists and is compatible with NestJS, it could be considered as an alternative or workaround until native support for this feature is available in `nestjs-prisma`.

### Environment:

- NestJS Version: ^10.0.0
- `nestjs-prisma` Version: ^0.23.0
- Prisma Version: latest

**Comment by marcjulian** [comment]
Hi this feature is already supported. Have a look at [Multiple Prisma Clients](https://nestjs-prisma.dev/docs/custom-prisma-client-location/#multiple-prisma-clients). If both Prisma schemas use a custom output location for the Prisma Client you need to use `CustomPrismaModule` and `CustomPrismaService` for both. 

```prisma
generator client {
  provider = "prisma-client-js"
  output = "../node_modules/@acme/prisma"
}
```

If one of the Prisma schemas uses the default output location for the Prisma Client you could use `PrismaModule` and `PrismaService` for the default location and use `CustomPrismaModule` and `CustomPrismaService` for the other Prisma Client.

Let me know if we can improve the docs.

**Comment by marcjulian** [comment]
I am closing this for now. Let me know if there is something to improvide.
