### ISSUE TITLE
How can we use it with ZenStack

### ISSUE THREAD

**Issue by HasanHaghniya** [notiz-dev/nestjs-prisma#91]
https://github.com/zenstackhq/zenstack

**Comment by marcjulian** [comment]
Hi @SecretKeeper I don't use ZenStack. Do you still use a regular `PrismaClient` with ZenStack?
If the PrismaClient is imported from `@prisma/client` follow [Basic usage](https://nestjs-prisma.dev/docs/basic-usage/).
If the PrismaClient is exported to a custom location or the client uses Extension follow [Custom Location](https://nestjs-prisma.dev/docs/custom-prisma-client-location/) and [Prisma Client Extensions](https://nestjs-prisma.dev/docs/prisma-client-extensions/).

You can always add ZenStack to the docs, when you figure out how to use it with nestjs-prisma.
