### ISSUE TITLE
Can we remove additional `client` field after use cutom client?

### ISSUE THREAD

**Issue by SnowingFox** [notiz-dev/nestjs-prisma#92]
for example, we want this
```ts
this.customPrismaService.user.findByEmail(email)
```

but now is this
```ts
this.customPrismaService.client.user.findByEmail(email)
```
we need write `client` field additional, so is there any method to remove this?

**Comment by marcjulian** [comment]
Hi @SnowingFox i haven't found a better solution for providing `CustomPrismaService` without the additional `client` field.  I have written about it in more details https://github.com/notiz-dev/nestjs-prisma/issues/88#issuecomment-1924445421
